name: Test

on: [push, pull_request]

jobs:
  ruby:
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["3.0", "3.1", "3.2", "head"]
        rails_version: ["main", "6-1-stable", "7-0-stable"]
        include:
          - ruby_version: jruby
            rails_version: 6-1-stable
          - ruby_version: jruby
            rails_version: 7-0-stable
    runs-on: ubuntu-latest
    name: Test on ${{ matrix.ruby_version }} with Rails ${{ matrix.rails_version }}
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true # install gems, and cache them
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
    - name: Run tests
      run: |
        bundle exec rake
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
